server:
  port: 8001

spring:
  application:
    name: service-edu   # 服务名，这里名字最好用-，不要用_（可能出现问题，项目名称无所谓）
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 33824
  jackson:
    # 返回JSON的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置mapper xml文件路径
  mapper-locations: classpath:com/andyron/eduservice/mapper/xml/*.xml

#logging:
#  level:
#    root: INFO  # 设置日志级别，默认就是INFO


# 开启熔断器
feign:
  hystrix:
    enabled: true
